project_id = "easrudmoidhnfrqchfwc"

[functions.recommend-jobs]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.import-jobs]
verify_jwt = false

[functions.notify-job-matches]
verify_jwt = false
schedule = "0 9 * * *"
